describe("check demo webshop",()=>{
    it("Verify that the header spelled correctly",()=>{
        cy.visit("https://demowebshop.tricentis.com/register")
        cy.get(".header-logo")
        cy.get(".ico-login")
        cy.get("#small-searchterms")
        cy.get("h1").contains("Register")
        cy.get("#gender-male")
        cy.get("#LastName")
        cy.contains("Email")
       cy.get(".block-category-navigation").contains("Gift Cards")
       cy.get(".title").contains("Manufacturers")
       cy.get("#register-button")
       cy.get("[name=NewsletterEmail]")
       cy.get("#newsletter-subscribe-button")
       cy.get(".my-account").contains("My account")
       cy.contains("Contact us")
       cy.get(".top-menu").contains("Jewelry")
    })
})